logging:
  level: INFO
  format: '[%(asctime)s] [%(levelname)s] [%(funcName)s()][%(lineno)s]: %(message)s'
  date_fmt: '%Y-%m-%d %H:%M:%S'
  handlers:
      console:
        class: logging.StreamHandler
        formatter: default
        stream: ext://sys.stdout
      file_handler:
        class: myLogger.handlers.CustomTimedRotatingFileHandler
        formatter: default
        filename: /var/log/calculus.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
  log_file: logs/calculus.log

server:
  host: 127.0.0.1
  port: 5000