from sympy import symbols, sqrt, init_printing, Integral, pretty_print, pretty, exp, pi, sin, \
    print_latex, simplify, solve, expand, latex, cos
import net_change as nc
import areas as ar
from fractions import Fraction
import numpy as np
import webbrowser
import sys
import os
from mpmath import e
from IPython.core.display import display, HTML, Math

init_printing(use_unicode=True)


#####################################################################
#                   Display Object
#####################################################################
def _display_(_obj_=object):
    """Display latex objects in generated webpage.

    :param _obj_: the latex object
    :return:
    """
    html = ("""
            <!DOCTYPE html>
            <html>
                <head>
                  <meta charset="utf-8">
                  <meta name="viewport" content="width=device-width">
                  <title>MathJax example</title>
                  <script id="MathJax-script" async 
                  src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
                                
                </head>
                <body>
                    <p>                        
                        {0}
                    </p>
                </body>                
            </html>""".format(_obj_))
    path = os.path.abspath('temp.html')
    url = 'file://' + path
    with open(path, 'w') as _file_:
        _file_.write(html)
    webbrowser.open(url)


#####################################################################
#####################################################################
#             Volume of Rectangular Prism
#####################################################################
def _rec_prism_(length, width, height) -> object:
    """Volume of a Rectangular Prism:

    V = lwh = length  width  height
    SA = 2lw * 2hw * 2lh
    SA = 2(length * width) + 2(height * width) + 2(length * height)
    
    :param length:
    :param width:
    :param height:
    :return:
    """
    _volume_ = length * width * height
    _surface_area_ = 2 * (length * width) + 2 * (height * width) + 2 * (length * height)
    return [_volume_, _surface_area_]


#####################################################################
#####################################################################
#                            Volume Using Disks 1
#####################################################################
def _volume_disk_(fx, lower_bound, upper_bound, variable_of_integration) -> object:
    """The Disk Method:
If a region in the plane is revolved about a line in the same
plane, the resulting object is known as a solid of revolution.
For example, a solid right circular cylinder can be generated by
revolving a rectangle. Similarly, a solid spherical ball can be
generated by revolving a semi-disk. The line about which we
rotate the shape is called the axis of revolution.
The disk method is used when we rotate a single curve y = f(x)
around the x or y axis. Suppose that y = f(x) is a continuous
non-negative function on the interval [a, b].
The volume of the solid formed by revolving the region bounded by
the curve  y - f(x) and the x-axis between x = a and x = b about
the x-axis is given by:

- V = π ∫ [a,b] [ f(x) ]^2 dx

The cross section perpendicular to the axis of revolution has
the form of a disk of radius R = f(x).
Similarly, we can find the volume of the solid when the region
is bounded by the curve x = f(y) and the y-axis between y = c
and y = d, and is rotated about the y-axis. The resulting formula is:

- V = π ∫ [c, d] [ f(y)]^2 dy

    :param fx: f(x) is the function on the interval
    :param lower_bound:
    :param upper_bound:
    :param variable_of_integration:
    :return:
    """
    r = fx
    a = lower_bound
    b = upper_bound
    _v_ = variable_of_integration
    c, d = symbols('c, d')
    _area_ = ar.circle_(r)
    _integral_ = Integral(_area_, (_v_, c, d))
    _integral_sol = Integral(_area_, (_v_, a, b))
    _solution_ = _integral_sol.doit()

    print("\nVolume of the region, Integral notation: \n")
    pretty_print(_integral_sol)
    print('\nThe antiderivative of the function with respect to {} is:\n'.format(_v_))
    pretty_print(_integral_.doit())
    print('\nVolume of the region is : \n')
    pretty_print(_solution_)


#####################################################################
#####################################################################
#     Volume Using Washers 1 - Around the x-Axis
#####################################################################
def _volume_washer_(fx, gx, lower_bound, upper_bound, variable_of_integration) -> object:
    """ The washer method:

If a region in the plane is revolved about a line in the same plane,
the resulting object is known as a solid of revolution. For example,
a solid right circular cylinder can be generated by revolving a rectangle.
Similarly, a solid spherical ball can be generated by revolving a semi-disk.
The line about which we rotate the shape is called the axis of revolution.
We can extend the disk method to find the volume of a hollow solid of revolution.
Assuming that the functions f(x) and g(x) are continuous and non-negative on
the interval [a,b] and g(x) ≤ f(x),  consider a region that is bounded
by two curves y = f(x) and y = g(x), between x = a and x = b.
The volume of the solid formed by revolving the region about the
x−axis is:

- V = π ∫ [a,b] ( [f(x)]^2 − [g(x)]^2 ) dx

At a point x on the x−axis, a perpendicular cross section of the
solid is washer-shape with the inner radius r = g(x) and the outer radius
R = f(x). The volume of the solid generated by revolving about the y−axis
a region between the curves x = f(y) and x = g(y), where g(y) ≤ f(y) and
c ≤ y ≤ d  is given by the formula:

- V = π ∫ [c,d] ( [f(y)]^2 − [g(y)]^2 ) dy

    :param fx: f(x) is the top curve
    :param gx: g(x) is the bottom curve
    :param lower_bound:
    :param upper_bound:
    :param variable_of_integration:
    :return:
    """
    a, b = symbols('a, b')
    _a_ = lower_bound
    _b_ = upper_bound
    _v_ = variable_of_integration
    if str(_v_) == "x":
        _l_ = "a"
        _u_ = "b"
    elif str(_v_) == "y":
        _l_ = "c"
        _u_ = "d"
    fx_area = ar.circle_(fx)
    gx_area = ar.circle_(gx)
    demo = Integral((fx_area - gx_area), (_v_, _l_, _u_))
    vol = Integral((fx_area - gx_area), (_v_, _a_, _b_))
    int_vol = vol.doit()
    print('\nf(x) = \n{0}'.format(pretty(fx)))
    print('\ng(x) = \n{0}'.format(pretty(gx)))
    print('\nArea of f(x) = \n')
    pretty_print(fx_area)
    print('\nArea of g(x) = \n')
    pretty_print(gx_area)
    print('\nIntegrate the Area of [ A(f({0})) - A(g({0})) ], over the bounds of '
          '{1} = {2} & {3} = {4}: \n'.format(_v_, _l_, _a_, _u_, _b_))
    pretty_print(demo)
    print('\nIntegrate the Area of [ A(f({0})) - A(g({0})) ], over the bounds of '
          '{1} = {2} & {3} = {4}: \n'.format(_v_, _l_, _a_, _u_, _b_))
    pretty_print(vol)
    print('\nFind the antiderivative of integration: \n')
    pretty_print(demo.doit())
    print('\nSolve for the volume over the bounded region R: \n')
    pretty_print(int_vol)


#####################################################################
#     Volumes by Cylindrical Shells: the Shell Method
#####################################################################
def _cylindrical_shell_(fx, gx, lower_bound, upper_bound, line_of_rotation,
                      variable_of_integration) -> object:
    """Volumes by Cylindrical Shells: the Shell Method.

 V = 2πrh Δr
    Another method of find the volumes of solids of revolution is the shell
method. It can usually find volumes that are otherwise difficult to evaluate
using the Disc / Washer method.

- General formula: V = ∫ 2π (shell radius)(shell height) dx

The Shell Method (about the y-axis)The volume of the solid generated by revolving
about the y-axis the region between the x-axis and the graph of a continuous function
y = f (x), a ≤ x ≤ b is:

- V = ∫ [a,b] 2π  [radius] * [shell height] dx = ∫ [a,b] 2π * x * f(x) dx

Similarly,

The Shell Method (about the x-axis) The volume of the solid generated by revolving
about the x-axis the region between the y-axis and the graph of a continuous function
x = f (y), c ≤ y ≤ d is:

- V = ∫ [c,d] 2π  [radius] * [shell height] dy = ∫ [c,d] 2π * y * f(y) dy

***Note: An easy way to remember which method to use to find the volume of a solid of
revolution is to note that the Disc / Washer method is used if the independent variable
of the function(s) and the axis of rotation is the same (e.g., the area under y = f (x),
revolved about the x-axis); while the Shell method should be used if the independent
variable is different from the axis of rotation (e.g., the area under x = f (y), revolved
about the x-axis).

    :param fx:
    :param gx:
    :param lower_bound:
    :param upper_bound:
    :param line_of_rotation:
    :param variable_of_integration:
    :return:
    """
    # noinspection DuplicatedCode
    _l_ = lower_bound
    _u_ = upper_bound
    _var_ = variable_of_integration
    _f_ = fx if fx is not None else gx
    _g_ = gx
    k = line_of_rotation if line_of_rotation is not None else None
    _radius_ = _var_ if k is None else (_var_ - k)
    _k_ = _radius_ if _radius_ is not None else _var_
    if _f_ is not None and _g_ is None:
        if _u_ is None:
            sol = solve(_f_)
            for aa in sol:
                if aa > 0:
                    _u_ = aa
        pretty_print(_u_)
        _v_ = Integral((2 * pi * _k_ * _f_), (_var_, _l_, _u_))
        _demo_ = Integral((2 * pi * _k_ * _f_), _var_)
        _demo_sol = _demo_.doit()
        print("\nIntegral: \n")
        pretty_print(_v_)
        print("\nSolution: \n")
        sol_v = _v_.doit()
        pretty_print(sol_v)
        return [_demo_, _demo_sol, _v_, sol_v]
    elif _f_ is not None and _g_ is not None:
        if _u_ is None:
            sol = solve(_g_ - _f_)
            for aa in sol:
                if aa > 0:
                    _u_ = aa
        pretty_print(_u_)
        _v_ = Integral((2 * pi * _radius_ * (_f_ - _g_)), (_var_, _l_, _u_))
        _demo_ = Integral((2 * pi * _radius_ * (_f_ - _g_)), _var_)
        _demo_sol = _demo_.doit()
        print("\nIntegral: \n")
        pretty_print(_v_)
        print("\nSolution: \n")
        sol_v = _v_.doit()
        pretty_print(sol_v)
        pretty_print(simplify(sol_v))
        return [_demo_, _demo_sol, _v_, sol_v]


#####################################################################
#           Arc Length
#####################################################################
def _arc_length_(fx, gx, lower_bound, upper_bound, line_of_rotation,
               variable_of_integration) -> object:
    """The Arc Length Function:

    If a smooth curve C has the equation y = f(x), a ≤ x ≤ b, let s(x) be the distance along C
    from the initial point P_0(a, f(a)) to the point Q(x, f(x)). Then s is a function, called
    the arc length function:

    - Arc Length = ∫ [a,b] √(1 + [f′(x)]^2)
dx.
    
    :param fx:
    :param gx:
    :param lower_bound:
    :param upper_bound:
    :param line_of_rotation:
    :param variable_of_integration:
    :return:
    """
    # noinspection DuplicatedCode
    _l_ = lower_bound
    _u_ = upper_bound
    _var_ = variable_of_integration
    _f_ = fx if fx is not None else gx
    _g_ = gx
    k = line_of_rotation if line_of_rotation is not None else None
    _radius_ = _var_ if k is None else (_var_ - k)
    _k_ = _radius_ if _radius_ is not None else _var_
    if _f_ is not None and _g_ is None:
        _f_der = _f_.diff(_var_)
        _f_arc = sqrt(1 + _f_der ** 2)
        _f_int = Integral(_f_arc, (_var_, _l_, _u_))
        sol_f_int = simplify(_f_int.doit())
        if isinstance(sol_f_int, float):
            print("simplified Fraction: \n")
            pretty_print(Fraction(sol_f_int).limit_denominator())
        _demo_ = Integral(_f_arc, _var_)
        _demo_sol = _demo_.doit()
        print("\nf'({}) = \n".format(_var_))
        pretty_print(_f_der)
        print("\nArc Length Function: \n")
        pretty_print(_demo_)
        print("\nUnbounded Antiderivative Solution of Arc Length: \n")
        pretty_print(_demo_sol)
        # print("\nArc Length")
        # pretty_print(_f_arc)
        print("\nBounded Arc Length: \n")
        pretty_print(_f_int)
        print("\nBounded Arc Length Solution: \n")
        pretty_print(simplify(sol_f_int))
    return [fx, _f_der, _demo_, _demo_sol, _f_int, sol_f_int]


#####################################################################
#     Area of a Surface of Revolution
#####################################################################
def _surface_area_of_revolution_(fx, gx, lower_bound, upper_bound, line_of_rotation,
                               variable_of_integration) -> object:
    """Area of a Surface of Revolution:

    A surface of revolution is obtained when a curve is rotated about an axis.
    We consider two cases – revolving about the x−axis and revolving about the
    y−axis.

    Revolving about the x−axis:

    Suppose that y(x), y(t), and y(θ) are smooth non-negative functions on the
    given interval.

    A1. If the curve y = f(x), a ≤ x ≤ b is rotated about the x−axis, then the surface
    area is given by:

    - A = 2π ∫ [a, b] f(x) √(1 + [f′(x)]^2) dx.

    A2. If the curve is described by the function x = g(y), c ≤ y ≤ d, and rotated
    about the x−axis, then the area of the surface of revolution is given by:

    - A = 2π ∫ [c, d] y √(1 + [g′(y)]^2) dy.

    A3. If the curve defined by the parametric equations x = x(t), y = y(t), with t
    ranging over some interval [α, β], is rotated about the x−axis, then the surface
    area is given by the following integral (provided that y(t) is never negative):

    - A = 2π ∫ [α, β] y(t) √([x′(t)]^2 + [y′(t)]^2) dt.

    A4. If the curve defined by polar equation r = r(θ), with θ ranging over some interval
    [α, β], is rotated about the polar axis, then the area of the resulting surface is
    given by the following formula (provided that y = r sin θ  is never negative):

    - A = 2π ∫ [α, β] r(θ) sin(θ) √([r(θ)]^2 + [r′(θ)]^2) dθ.

    Revolving about the y−axis:

    Suppose that g(y), x(t), and x(θ) are smooth non-negative functions on the
    given interval.

    B1. If the curve y = f(x), a ≤ x ≤ b is rotated about the y−axis, then the surface
    area is given by:

    - A = 2π ∫ [a, b] x √(1 + [f′(x)]^2) dx.

    B2. If the curve is described by the function x = g(y), c ≤ y ≤ d, and rotated
    about the y−axis, then the area of the surface of revolution is given by:

    - A = 2π ∫ [c, d] g(y) √(1 + [g′(y)]^2) dy.

    B3. If the curve defined by the parametric equations x = x(t), y = y(t), with t
    ranging over some interval [α, β], is rotated about the y−axis, then the surface
    area is given by the following integral (provided that x(t) is never negative):

    - A = 2π ∫ [α, β] x(t) √([x′(t)]^2 + [y′(t)]^2) dt.

    B4. If the curve defined by polar equation r = r(θ), with θ ranging over some interval
    [α, β], is rotated about y-axis, then the area of the resulting surface is
    given by the following formula (provided that x = r sin θ  is never negative):

    - A = 2π ∫ [α, β] r(θ) cos(θ) √([r(θ)]^2 + [r′(θ)]^2) dθ.

    :param fx:
    :param gx:
    :param lower_bound:
    :param upper_bound:
    :param line_of_rotation:
    :param variable_of_integration:
    :return:
    """
    _l_ = lower_bound
    _u_ = upper_bound
    _var_ = variable_of_integration
    _f_ = fx if fx is not None else gx
    _g_ = gx
    k = line_of_rotation if line_of_rotation is not None else None
    _radius_ = _var_ if k is None else (_var_ - k)
    _k_ = _radius_ if _radius_ is not None else _var_
    if _f_ is not None and _g_ is None:
        _f_der = _f_.diff(_var_)
        _f_arc = simplify(2 * pi * _f_ * sqrt(1 + _f_der ** 2))
        _f_int = Integral(_f_arc, (_var_, _l_, _u_))
        sol_f_int = simplify(_f_int.doit())
        _demo_ = Integral(_f_arc, _var_)
        _demo_sol = _demo_.doit()
        print("\nf({}) = \n".format(_var_))
        pretty_print(_f_)
        print("\nf'({}) = \n".format(_var_))
        pretty_print(_f_der)
        print("\nArc Length Function: \n")
        pretty_print(_demo_)
        print("\nUnbounded Antiderivative Solution of Arc Length: \n")
        pretty_print(_demo_sol)
        # print("\nArc Length")
        # pretty_print(_f_arc)
        print("\nBounded Arc Length: \n")
        pretty_print(_f_int)
        print("\nBounded Arc Length Solution: \n")
        pretty_print(simplify(sol_f_int))
        print(sol_f_int)
        print("\nExpanded Solution: \n")
        pretty_print(expand(sol_f_int))
        return [fx, _f_der, _demo_, _demo_sol, _f_int, sol_f_int]


#####################################################################
#     Mass and Density 1 - Linear Density
#####################################################################
def _linear_density_(px, lower_bound, upper_bound, variable_of_integration) -> object:
    """

    Let R denote a region bounded above by the graph of a continuous function
    f(x), below by the x-axis, and on the left and right by the lines x = a
    and x = b, respectively. Let ρ denote the density of the associated lamina.
    Then we can make the following statements:

    - i. The mass of the lamina is:
        - m = ρ ∫ [a, b] f(x)dx

    - ii. The moments M_x and M_y of the lamina with respect to the x-axis and y-axes,
            respectively, are
        - M_x = ρ ∫ [a, b] [f(x)]^2/2 dx
        and
        - M_y = ρ ∫ [a, b] x f(x) dx

    - iii. The coordinates of the center of mass ( X̅, y̅ ) are:
        - X̅ = M_y/m  and  y̅ = M_x/m



    :param px:
    :param lower_bound:
    :param upper_bound:
    :param variable_of_integration:
    :return:
    """
    _l_ = lower_bound
    _u_ = upper_bound
    _var_ = variable_of_integration
    _mass_ = Integral(px, (_var_, _l_, _u_))
    _mass_sol_ = _mass_.doit()
    print("\nIntegral mass: \n")
    pretty_print(_mass_)
    print("\nMass of the object: \n")
    pretty_print(_mass_sol_)
    return [_mass_, _mass_sol_]


#####################################################################
# Mass of a Two-Dimensional Object From Its Radial Density Function
#####################################################################
def _radial_density_(px, radius, variable_of_integration) -> object:
    """

    We need to recall how to calculate the mass of a circular object
    from its radial density function.

    Let ρ(x) be an integrable function representing the radial density
    of a disk of radius r. Then the mass of the disk is given by:

    - m = ∫ [0, r] 2π x ρ(x) dx.

    :param px:
    :param radius:
    :param variable_of_integration:
    :return:
    """
    x, b = symbols('x, b')
    _l_ = 0
    _u_ = radius
    _var_ = variable_of_integration
    _mass_ = Integral(2 * pi * x * px, (_var_, _l_, _u_))
    _demo_ = Integral(2 * pi * x * px, (_var_, _l_, b))
    _mass_sol_ = _mass_.doit()
    print("\nIntegral mass: \n")
    pretty_print(_mass_)
    print("\nMass of the object: \n")
    pretty_print(_demo_.doit())
    print("\nMass of the object: \n")
    pretty_print(_mass_sol_)
    return [_mass_, _mass_sol_]

    #####################################################################
    #####################################################################
    #                           Main Method
    #####################################################################


# if __name__ == "__main__":
#     #     # main method
#     x, y, t = symbols('x, y, t')
#     f = 3 + exp(3*x**2)
#     g = None
#     # a = 2
#     # b = 6
#     _radius_ = 3
#     _variable_ = x
#     _radial_density_(f, _radius_, _variable_)
